### Send POST request with json body
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/annie?annotations=:Token
Content-Type: text/plain
Accept: application/json

Hello World!

### Send POST request with json body
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/annie/
Content-Type: text/json
Accept: application/json

{
  "text": "Hello World!"
}

### Send POST request for gate+xml
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/annie/
Content-Type: text/json
Accept: application/gate+xml

{
  "text": "This is some random text using JSON"
}

### Send POST request for gate+xml
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/annie/
Content-Type: text/json
Accept: application/fastinfoset

{
  "text": "This is some random text using JSON 1"
}
