### Send POST request with json body
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/execute/
Content-Type: application/fastinfoset
Accept: application/json

< ./hello-world.finf
> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
client.test("Response is of correct type.", function() {
  client.assert(response.contentType.mimeType === "application/json", "Content-Type is not application/json")
});
client.test("Response text Matches.", function() {
  client.assert(response.body.text === "Hello World!", "Text is of the right type!")
});
%}

### Same with GATE XML Response
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/execute/
Content-Type: application/fastinfoset
Accept: application/gate+xml

< hello-world.finf

### Same with GATE XML Response
POST https://mh4gdixkm7.execute-api.us-east-1.amazonaws.com/Prod/execute/
Content-Type: application/fastinfoset
Accept: application/fastinfoset

< hello-world.finf