AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zeroae.gate

  A GATE Application served over lambda.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    BinaryMediaTypes:
      - "application~1fastinfoset"
      - "application~1tika"
  Function:
    Timeout: 120

Resources:
  LambdaGateApp:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: co.zeroae.gate.App::handleRequest
      Runtime: java8.al2
      MemorySize: 1024
      Layers:
        - arn:aws:lambda:us-east-1:162714053306:layer:zae-lambda-java-gate:8
        - arn:aws:lambda:us-east-1:162714053306:layer:zae-lambda-runtime-wrapper:1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bin/wrapper.sh
          AWS_LAMBDA_EXEC_WRAPPER_EXCLUDE_ARGS: >-
            -XX:+UseSerialGC
          GATE_APP_NAME: application
          GATE_APP_COST_PER_REQUEST: 1
          GATE_APP_DAILY_QUOTA: 10000
          GATE_APP_DEFAULT_ANNOTATIONS: :Address, :Date, :Location, :Organization, :Person
          GATE_APP_ADDITIONAL_ANNOTATIONS: :Money, :Percent, :Token, :SpaceToken, :Sentence
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        Execute:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /annie
            Method: post
        GetMetadata:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /annie/metadata
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaGateAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Gate Application"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/annie/"
  LambdaGateApp:
    Description: "Gate Application ARN"
    Value: !GetAtt LambdaGateApp.Arn
  LambdaGateAppIamRole:
    Description: "Implicit IAM Role created for Gate Application"
    Value: !GetAtt LambdaGateAppRole.Arn
