name: AWS SAM Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with SAM
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: sam build
      - name: Publish with SAM
        uses: tkt-actions/aws-sam-cli@v1
        with:
          cmd: |
            git_version=
            sam deploy --parameter-overrides "Version=$(git describe --tags)"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
